# packages in environment at /home/pi/miniconda:
#
anaconda-client           1.0.2                    py27_0  
click                     6.7                       <pip>
clyent                    0.4.0                    py27_0  
conda                     3.18.3                   py27_0  
conda-env                 2.4.4                    py27_0  
decorator                 4.0.2                    py27_0  
freetype                  2.5.2                         2  
ipython                   4.0.0                    py27_0  
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py27_0  
jpeg                      8d                            0  
libgfortran               1.0                           0  
libpng                    1.6.17                        0  
libtiff                   4.0.2                         1  
numpy                     1.9.2                    py27_1  
openblas                  0.2.14                        1  
openssl                   1.0.2d                        0  
path.py                   7.6.1                    py27_0  
pexpect                   3.3                      py27_0  
pickleshare               0.5                      py27_0  
pillow                    2.9.0                    py27_0  
pip                       7.1.2                    py27_0  
pycosat                   0.6.1                    py27_0  
pycrypto                  2.6.1                    py27_0  
python                    2.7.10                        2  
python-dateutil           2.4.2                    py27_0  
pytz                      2015.4                   py27_0  
pyyaml                    3.11                     py27_1  
readline                  6.2                           2  
requests                  2.8.1                    py27_0  
rpi.gpio                  0.6.2                    py27_0  
setuptools                18.4                     py27_0  
simplegeneric             0.8.1                    py27_0  
six                       1.9.0                    py27_0  
sqlite                    3.8.4.1                       1  
traitlets                 4.0.0                    py27_0  
w1thermsensor             1.0.4                     <pip>
wheel                     0.26.0                   py27_1  
yaml                      0.1.6                         0  
zlib                      1.2.8                         0  
