name: pi2
dependencies:
- decorator=4.0.2=py27_0
- ipython=4.0.0=py27_0
- ipython_genutils=0.1.0=py27_0
- openssl=1.0.2d=0
- path.py=7.6.1=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=7.1.2=py27_0
- python=2.7.10=2
- readline=6.2=2
- rpi.gpio=0.6.2=py27_0
- setuptools=18.4=py27_0
- simplegeneric=0.8.1=py27_0
- sqlite=3.8.4.1=1
- traitlets=4.0.0=py27_0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- pip:
  - ipython-genutils==0.1.0

